export const EXPENSE_CATEGORIES = [
  "C-Suite Reward",
  "Client – Bfast/Lunch",
  "Client – Dinner/HH",
  "Client – Entertainment",
  "ENRG Expenses",
  "EVGRN – Non Billable Project",
  "External Event",
  "IG Office Parking",
  "INP – Nurses",
  "Internal – 1x1 Development",
  "Internal – Compass",
  "Internal – Team Celebration",
  "MON – Billable to Client",
  "Other - Bereavement",
  "Other - Software Fees",
  "Other - Supplies/Shipping",
  "Other - Training Course",
  "Philanthropy - Internal",
  "Philanthropy - OWH Trips",
  "Phone Allowance",
  "Recruiting - Candidate Interview",
  "Recruiting - Career Fair",
  "Recruiting - Sponsorships/Competitions",
  "Shared Values Week",
  "Attendee Travel Meal",
  "Travel (Client) – Airfare, Hotel/Lodging, Rental Car",
  "Travel (Compass) – Airfare, Hotel/Lodging, Rental Car",
  "Travel (Contest Trip) – Airfare, Airport Parking, Rideshare/Train",
  "Travel (External Event) – Airfare, Hotel/Lodging, Rental Car",
  "Travel (Legacy Conference) – Airfare, Airport Parking, Rideshare/Train",
  "Travel (Other) – Airfare, Hotel/Lodging, Rental Car",
  "Travel (Remote) – Airfare, Hotel/Lodging, Rental Car",
  "Travel (TITAN) – Airfare, Airport Parking, Checked Baggage, Rideshare/Train",
  "Travel (WLC) – Airfare, Hotel/Lodging, Rental Car",
  "Travel - Airport Parking",
  "Travel - IT Office Set Up",
  "Travel - Mileage",
  "Travel - Offsite Parking",
  "Travel - Onsite Staff – Airfare, Transportation, Travel Meals",
  "Travel - Personal Meal",
  "Travel - Tolls",
  "Travel - Uber/Lyft/Train",
  "Travel - Wi-Fi/Bags",
  "WLC - Event",
  "IGU Training - Airport Parking",
  "IGU Training - Personal Meals",
  "IGU Training - Uber/Lyft/Train",
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];
